# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Maven Package

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v2

    - name: Use Cache for Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Import GPG keys
      run: 'echo -e "$GPG_FILE" | gpg2 --import --no-tty --batch --yes'
      shell: bash
      env:
        GPG_FILE: ${{secrets.GPG_FILE}}

    - name: Set up Java for Apache Maven Central
      uses: actions/setup-java@v4
      with:
        java-version: 11
        distribution: temurin
        cache: maven
        server-id: central # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: MAVEN_CENTRAL_USER  # env variable for username in deploy
        server-password: MAVEN_CENTRAL_PASSWORD  # env variable for token in deploy
        gpg-passphrase: MAVEN_GPG_PASSPHRASE  # env variable for GPG private key passphrase

    - name: Build and Verify with Maven
      run: mvn --batch-mode --update-snapshots clean compile verify

    - name: Publish to Apache Maven Central
      # run: mvn deploy --batch-mode --update-snapshots -P sign,!build-extras -Dmaven.test.skip=true
      run: mvn deploy --batch-mode --update-snapshots -P sign,!build-extras,deploy-ossrh -Dmaven.test.skip=true
      env:
        MAVEN_CENTRAL_USER: ${{ secrets.MAVEN_CENTRAL_USER }}
        MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

    - name: Set up Java for publishing to GitHub Packages
      uses: actions/setup-java@v4
      with:
        java-version: 11
        distribution: temurin
        cache: maven
        
    - name: Publish to GitHub Packages
    #  -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/csowada/ebus
      run: mvn deploy --batch-mode --update-snapshots -P !sign,!build-extras,!deploy-ossrh,deploy-github -Dmaven.test.skip=true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create a new GitHub Release
      uses: docker://antonyurchenko/git-release:latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DRAFT_RELEASE: "true"
        PRE_RELEASE: "false"
        CHANGELOG_FILE: "CHANGELOG.md"
        ALLOW_EMPTY_CHANGELOG: "true"
        # ALLOW_TAG_PREFIX: "true"
      with:
        args: |
          target/*.jar